export const Classes = [
  { class: "6 ශ්‍රේණිය" },
  { class: "7 ශ්‍රේණිය" },
  { class: "8 ශ්‍රේණිය" },
  { class: "9 ශ්‍රේණිය" },
  { class: "10 ශ්‍රේණිය" },
  { class: "11 ශ්‍රේණිය" },
];

// =============================== GRADE 6 ==================================
export const Grade6 = [
  {
    grade: "6 ශ්‍රේණිය",
    subject: "ගණිතය",
    description: "6 ශ්‍රේණිය ගණිතය කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1hzDpSzZxoXRFzr9brBtSilBWdqusR_i8",
    img: "/grade6/grade6-math",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "විද්‍යාව",
    description: "6 ශ්‍රේණිය විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "13K4QO2MSCRmJQTlSyXuvZ3r57XApbOWI",
    img: "/grade6/grade6-science",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "සිංහල",
    description: "6 ශ්‍රේණිය සිංහල කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1eKUp8GPXQWPaQdafZ4nNrp_y7QE_-mVp",
    img: "/grade6/grade6-sinhala",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "ඉංග්‍රීසි",
    description: "6 ශ්‍රේණිය ඉංග්‍රීසි කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1tL6nKLTVDDPeg-qhXDUqUtyZV8cVqiJC",
    img: "/grade6/grade6-english",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "බුද්ධ ධර්මය ",
    description: "6 ශ්‍රේණිය බුද්ධ ධර්මය කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1r72HPIDoe7dWanr7XyjkwmNq6pgrUfgl",
    img: "/grade6/grade6-buddhism",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "ඉතිහාසය",
    description: "6 ශ්‍රේණිය ඉතිහාසය කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1YROShMizGwM5N4Sro0ipWoAGPtTj5F8X",
    img: "/grade6/grade6-history",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "පුරවැසි අධ්‍යාපනය",
    description: "6 ශ්‍රේණිය පුරවැසි අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "19tZ9HU71st50OqTPxgvD790iq_GD-LBI",
    img: "/grade6/grade6-civic",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "භූගෝල විද්‍යාව",
    description: "6 ශ්‍රේණිය භූගෝල විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1AsJYnARpPonFOTbtdJrkZ4ih2q7vWQB7",
    img: "/grade6/grade6-geography",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය",
    description:
      "6 ශ්‍රේණිය සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1nKziXvhApyzFBmBCTAZgs3PMNPeZOabM",
    img: "/grade6/grade6-health",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "චිත්‍ර",
    description: "6 ශ්‍රේණිය චිත්‍ර කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1xkrWeZxgJSP8BMjcstr16zgY8IClqZus",
    img: "/grade6/grade6-art",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "නැටුම්",
    description: "6 ශ්‍රේණිය නැටුම් කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1h1asF2IkewoS-bZHcayQnBoTMyaZEtHs",
    img: "/grade6/grade6-dance",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "සංගීතය",
    description: "6 ශ්‍රේණිය සංගීතය කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1tTfv5_uISU9InyZ6BMENjmPNqHCFK7nh",
    img: "/grade6/grade6-music",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "නාට්‍ය හා රංග කලාව",
    description: "6 ශ්‍රේණිය නාට්‍ය හා රංග කලාව කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "132Z7XXdbUYIL0fNKGiBNHd1A9H_VDRfg",
    img: "/grade6/grade6-drama",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "ප්‍රායෝගික තාක්ෂණික කුසලතා",
    description:
      "6 ශ්‍රේණිය ප්‍රායෝගික තාක්ෂණික කුසලතා කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1llkpmtPcnfl7ZDsvNU7VuY7O-MxLGo0L",
    img: "/grade6/grade6-pts",
  },
  {
    grade: "6 ශ්‍රේණිය",
    subject: "තොරතුරු හා සන්නිවේදන තාක්ෂණය",
    description:
      "6 ශ්‍රේණිය තොරතුරු හා සන්නිවේදන තාක්ෂණය කාර්ය පත්‍රිකා සංග්‍රහය",
    link: "1E3PlglbCI2zjrUtJD8nXgJooOeEfHbMC",
    img: "/grade6/grade6-ict",
  },
];

// =============================== GRADE 7 ==================================
export const Grade7 = [
  {
    grade: "7 ශ්‍රේණිය",
    subject: "ගණිතය",
    description: "7 ශ්‍රේණිය ගණිතය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1fYbIICLXhtRyAkk06EcZmCpRwbTiwrz7",
    img: "/grade7/grade7-math",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "විද්‍යාව",
    description: "7 ශ්‍රේණිය ගණිතය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1-KrPJA03mFgWWcJKWHJQLhx2L96s7dOC",
    img: "/grade7/grade7-science",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "සිංහල",
    description: "7 ශ්‍රේණිය සිංහල කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1dKY0OWLZZ07Z6lKrwfKNkA_F7wYzN1oA",
    img: "/grade7/grade7-sinhala",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "ඉංග්‍රීසි ",
    description: "7 ශ්‍රේණිය ඉංග්‍රීසි කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1mVkMY6IpPx7ntb17YkBFLuG0TXFzhOR-",
    img: "/grade7/grade7-english",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "බුද්ධ ධර්මය",
    description: "7 ශ්‍රේණිය බුද්ධ ධර්මය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1vvFPqmcCIpT-uAcPjUb9ypoyTbNin4SQ",
    img: "/grade7/grade7-buddhism",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "ඉතිහාසය",
    description: "7 ශ්‍රේණිය ඉතිහාසය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "188Lt0OgA01y5sRqLNiNQh9AYn8QJsY_k",
    img: "/grade7/grade7-history",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "පුරවැසි අධ්‍යාපනය",
    description: "7 ශ්‍රේණිය පුරවැසි අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1_4PCPWTlm4faTaUHe7piKvP6OHJ0M3qc",
    img: "/grade7/grade7-civic",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "භූගෝල විද්‍යාව",
    description: "7 ශ්‍රේණිය භූගෝල විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1Rj04f9vl24HWWZkjSI9WeqQPMbjhPc85",
    img: "/grade7/grade7-geography",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "දෙවන භාෂාව දෙමළ",
    description: "7 ශ්‍රේණිය දෙවන භාෂාව දෙමළ කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1p6p2QdiwTKhgIWnIITDf2gSGdkkBgTuB",
    img: "/grade7/grade7-tamil",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය",
    description:
      "7 ශ්‍රේණිය සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1yQ06GJ6IHiqkJurFmcu8bWyeHpJkHIVZ",
    img: "/grade7/grade7-health",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "චිත්‍ර",
    description: "7 ශ්‍රේණිය චිත්‍ර කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1Z4Cx7eFFYDgunmUEi5zKQMWQ2g3NbEZ4",
    img: "/grade7/grade7-art",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "නැටුම් ",
    description: "7 ශ්‍රේණිය නැටුම් කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1WXMhtUKPJ92yVY9GOFvFT7UbZ5vlvRjI",
    img: "/grade7/grade7-dance",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "සංගීතය ",
    description: "7 ශ්‍රේණිය සංගීතය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1KmKv-xQ-dybba05YZDVTNpWU--Svhapf",
    img: "/grade7/grade7-music",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "නාට්‍ය හා රංග කලාව ",
    description: "7 ශ්‍රේණිය නාට්‍ය හා රංග කලාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1dJdwLmZS42euFoM8GNBX1gqIss9du3Vk",
    img: "/grade7/grade7-drama",
  },
  {
    grade: "7 ශ්‍රේණිය",
    subject: "ප්‍රායෝගික තාක්ෂණික කුසලතා ",
    description:
      "7 ශ්‍රේණිය ප්‍රායෝගික තාක්ෂණික කුසලතා කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1E10E4YFJ4O82vBFkAkBKA6qjth5OZfsE",
    img: "/grade7/grade7-pts",
  },
];

// =============================== GRADE 8 ==================================
export const Grade8 = [
  {
    grade: "8 ශ්‍රේණිය",
    subject: "ගණිතය",
    description: "8 ශ්‍රේණිය ගණිතය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "12Ae3P-zi7fy7_MJeWhWEgD4u67zx4Gv1",
    img: "/grade8/grade8-math",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "විද්‍යාව",
    description: "8 ශ්‍රේණිය විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1f7PSoQv9qK4N_T08tWUpD2sVBy1Qt06_",
    img: "/grade8/grade8-science",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "සිංහල",
    description: "8 ශ්‍රේණිය සිංහල කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1wuGPbH_DfGzcPxRvBZ3iqV9Jguc9eYw1",
    img: "/grade8/grade8-sinhala",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "ඉංග්‍රීසි",
    description: "8 ශ්‍රේණිය ඉංග්‍රීසි කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1O1_r0y8H1Sfc2ptgdDU4SQRFjQYcHdnQ",
    img: "/grade8/grade8-english",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "බුද්ධ ධර්මය",
    description: "8 ශ්‍රේණිය බුද්ධ ධර්මය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1BAUBTg_m4ntIhpD90XguP4WpPwK91qPM",
    img: "/grade8/grade8-buddhism",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "ඉතිහාසය",
    description: "8 ශ්‍රේණිය ඉතිහාසය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1rQAN9dM8iTmuYX-TtVXOTUmu1P2b7mKB",
    img: "/grade8/grade8-history",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "පුරවැසි අධ්‍යාපනය",
    description: "8 ශ්‍රේණිය පුරවැසි අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1uAwe-xJyZP39HR14CrCgGsxCsZ2Nw7ps",
    img: "/grade8/grade8-civic",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "භූගෝල විද්‍යාව",
    description: "8 ශ්‍රේණිය භූගෝල විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1mvzrKp4wD7mPXQikub16JYBcxFpICNo_",
    img: "/grade8/grade8-geography",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "දෙවන භාෂාව දෙමළ",
    description: "8 ශ්‍රේණිය දෙවන භාෂාව දෙමළ කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1divYKkw70kfBqOu_kvnSenrWZzWDyMOC",
    img: "/grade8/grade8-tamil",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය",
    description:
      "8 ශ්‍රේණිය සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1BmeXzPNFb9fxa0I35OkSEYLz1JtU-C8f",
    img: "/grade8/grade8-health",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "චිත්‍ර",
    description: "8 ශ්‍රේණිය චිත්‍ර කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1u1Six48SlL96kwL6jJ5HtFybr8YdM35p",
    img: "/grade8/grade8-art",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "නැටුම් ",
    description: "8 ශ්‍රේණිය නැටුම් අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1YN2PCkq2MrZ1oMZoC2tY1jyjczmEZ2BL",
    img: "/grade8/grade8-dance",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "නැටුම් (III වාරය)",
    description:
      "8 ශ්‍රේණිය නැටුම් (III වාරය) අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "10SSMtqAKe1N9ZV5uJgvwZDAkd0gZer2V",
    img: "/grade8/grade8-dance",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "සංගීතය",
    description: "8 ශ්‍රේණිය සංගීතය අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1p7Z0r-jySCK3TnZpKust5cVtCvUW695t",
    img: "/grade8/grade8-music",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "නාට්‍ය හා රංග කලාව",
    description:
      "8 ශ්‍රේණිය නාට්‍ය හා රංග කලාව අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1la0ovTgU3iLXn4Z6o29EwK2mgNHBp02P",
    img: "/grade8/grade8-drama",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "ප්‍රායෝගික තාක්ෂණික කුසලතා",
    description:
      "8 ශ්‍රේණිය ප්‍රායෝගික තාක්ෂණික කුසලතා අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1VmNwxdIaE_fVulynwwvUKc1mqVmOO-7b",
    img: "/grade8/grade8-pts",
  },
  {
    grade: "8 ශ්‍රේණිය",
    subject: "තොරතුරු හා සන්නිවේදන තාක්ෂණය",
    description:
      "8 ශ්‍රේණිය තොරතුරු හා සන්නිවේදන තාක්ෂණය අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1b6r3JpUiYytYPggJUf5d95NeNoQ94zlk",
    img: "/grade8/grade8-ict",
  },
];

// =============================== GRADE 9 ==================================
export const Grade9 = [
  {
    grade: "9 ශ්‍රේණිය",
    subject: "ගණිතය",
    description: "9 ශ්‍රේණිය ගණිතය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1_vrLPvemUyvmiv1XDr9ukaidV0E9yqqZ",
    img: "/grade9/grade9-math",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "විද්‍යාව",
    description: "9 ශ්‍රේණිය විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1sDU53bfKD0msPxdmyaYBs7fl-Iw2-N9q",
    img: "/grade9/grade9-science",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "සිංහල",
    description: "9 ශ්‍රේණිය සිංහල කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1_gQaTZRTDKEkby6OrN0XjRT9dfbsWbtu",
    img: "/grade9/grade9-sinhala",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "ඉංග්‍රීසි",
    description: "9 ශ්‍රේණිය ඉංග්‍රීසි කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1U4BlXmwhNW6kJX9S75Vrb53ERNrLqI08",
    img: "/grade9/grade9-english",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "බුද්ධ ධර්මය",
    description: "9 ශ්‍රේණිය බුද්ධ ධර්මය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1Qh9ryma4zDGoMh1_-HrYxHaxwAGJx3eP",
    img: "/grade9/grade9-buddhism",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "ඉතිහාසය",
    description: "9 ශ්‍රේණිය ඉතිහාසය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1YXg4U0STYOHcgMdZG9taLrgpWdd6h47O",
    img: "/grade9/grade9-history",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "පුරවැසි අධ්‍යාපනය",
    description: "9 ශ්‍රේණිය පුරවැසි අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1V69RNU2JBDrfqhPCe4Q7NJ_eG7vFgDym",
    img: "/grade9/grade9-civic",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "භූගෝල විද්‍යාව",
    description: "9 ශ්‍රේණිය භූගෝල විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1EcVrfK8A78NeqeTAnaMzKFDObh2j6Tnq",
    img: "/grade9/grade9-geography",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "දෙවන භාෂාව දෙමළ",
    description: "9 ශ්‍රේණිය දෙවන භාෂාව දෙමළ කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1HUNnEhKMJMjjYS9xEPPgRLxGZ4aYEZ8E",
    img: "/grade9/grade9-tamil",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය",
    description:
      "9 ශ්‍රේණිය සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1kdpxvdPSvn6LqHtfVVhPHlHud-iTBqcQ",
    img: "/grade9/grade9-health",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "චිත්‍ර",
    description: "9 ශ්‍රේණිය චිත්‍ර අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "17WIQxupfNo6nKJqM0w5m_-HWDQf-BfZz",
    img: "/grade9/grade9-art",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "නැටුම්",
    description: "9 ශ්‍රේණිය නැටුම් අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1PecERY84k1OVzhzBnXvlzA-2V_oFjRFb",
    img: "/grade9/grade9-dance",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "නැටුම් (II වාරය)",
    description:
      "9 ශ්‍රේණිය නැටුම් (II වාරය) අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1s3QdoidKuVDcZqSHrxhbGxw9MF2LTf62",
    img: "/grade9/grade9-dance",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "සංගීතය",
    description: "9 ශ්‍රේණිය නැටුම් සංගීතය අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "14Oljz54Y1DvRgQAfC8OjCHxPeL8_m8Zi",
    img: "/grade9/grade9-music",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "නාට්‍ය හා රංග කලාව",
    description:
      "9 ශ්‍රේණිය නාට්‍ය හා රංග කලාව අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "11S-v-INA9PTTteDTR8Ipd860FGj4ts-m",
    img: "/grade9/grade9-drama",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "ප්‍රායෝගික තාක්ෂණික කුසලතා",
    description:
      "9 ශ්‍රේණිය ප්‍රායෝගික තාක්ෂණික කුසලතා අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1xql0iaai_iY0YlitJR5bpDbxmLFoYa-Z",
    img: "/grade9/grade9-pts",
  },
  {
    grade: "9 ශ්‍රේණිය",
    subject: "තොරතුරු හා සන්නිවේදන තාක්ෂණය",
    description:
      "9 ශ්‍රේණිය තොරතුරු හා සන්නිවේදන තාක්ෂණය අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "125DDPHTQUL6-SKZfRZCd1CyuG-4Q156J",
    img: "/grade9/grade9-ict",
  },
];

// =============================== GRADE 10 ==================================
export const Grade10 = [
  {
    grade: "10 ශ්‍රේණිය",
    subject: "ගණිතය",
    description: "10 ශ්‍රේණිය ගණිතය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "12JHhZcxgt6AvSBH54WlE_8aquIuS4ZaD",
    img: "/grade10/grade10-math",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "විද්‍යාව",
    description: "10 ශ්‍රේණිය විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1x19DGdkbq771hxqzCFsWVAyrCSEJgJKV",
    img: "/grade10/grade10-science",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "සිංහල",
    description: "10 ශ්‍රේණිය සිංහල කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1Sn_S0zw14fUns8RxxGZXwNbKuCdSFHeJ",
    img: "/grade10/grade10-sinhala",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "ඉංග්‍රීසි",
    description: "10 ශ්‍රේණිය ඉංග්‍රීසි කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "13_WmpZC9kUKpiMafGYKlGr253UJ9Wla4",
    img: "/grade10/grade10-english",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "බුද්ධ ධර්මය",
    description: "10 ශ්‍රේණිය බුද්ධ ධර්මය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "13_Hu9kA179gHvt7vaufZJFvonmQlPjyn",
    img: "/grade10/grade10-buddhism",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "ඉතිහාසය",
    description: "10 ශ්‍රේණිය ඉතිහාසය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1TODbvRnA2XAfA0p5_AOb6Yc5ywi28hM7",
    img: "/grade10/grade10-history",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "පුරවැසි අධ්‍යාපනය",
    description: "10 ශ්‍රේණිය පුරවැසි අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1NcurOeanvsPIn4vXxD47B1nT7wvCar3I",
    img: "/grade10/grade10-civic",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "භූගෝල විද්‍යාව",
    description: "10 ශ්‍රේණිය භූගෝල විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1OrAR06SR8Pxbw0RRRHByjai1FTwHK7wH",
    img: "/grade10/grade10-geography",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "ව්‍යවසායකත්ව අධ්‍යනය",
    description: "10 ශ්‍රේණිය ව්‍යවසායකත්ව අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1LuIvnHFEfYA1WVgOFG5355ML_Yrqa5CF",
    img: "/grade10/grade10-entrepreneurship",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "ව්‍යාපාර හා ගිණුම්කරණ අධ්‍යනය",
    description:
      "10 ශ්‍රේණිය ව්‍යාපාර හා ගිණුම්කරණ අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1l8PUneDYTeyeVahQ0a18yGGZ1FNAE7fA",
    img: "/grade10/grade10-business",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "දෙවන භාෂාව දෙමළ",
    description: "10 ශ්‍රේණිය දෙවන භාෂාව දෙමළ අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "14vI29DUJW7Ywe49cQz5FDbTExt1o0-O9",
    img: "/grade10/grade10-tamil",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "සිංහල සාහිත්‍ය",
    description: "10 ශ්‍රේණිය සිංහල සාහිත්‍ය අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1lvPQIcpyzQPwlCIU8BZmM_u81u1n1etO",
    img: "/grade10/grade10-sinhalaLit",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "චිත්‍ර",
    description: "10 ශ්‍රේණිය චිත්‍ර අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "14L6TlT5ItrJptdc9sLCcMJtV_wWFu9dv",
    img: "/grade10/grade10-art",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "නැටුම්",
    description: "10 ශ්‍රේණිය නැටුම් අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1ILqYBVOvTjsG1HNXFkZCF4Bkk8VTjKZH",
    img: "/grade10/grade10-dance",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "සංගීතය",
    description: "10 ශ්‍රේණිය සංගීතය අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1p13J0AF_BxeRq4eJzZvUQf0_OADOx8Gf",
    img: "/grade10/grade10-music",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "නාට්‍ය හා රංග කලාව",
    description:
      "10 ශ්‍රේණිය නාට්‍ය හා රංග කලාව අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1zjHbcUGeNPnEYbirbneymFNx90F83kMQ",
    img: "/grade10/grade10-drama",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "කෘෂිකර්මය",
    description: "10 ශ්‍රේණිය කෘෂිකර්මය අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1ieJ-XFXC5JNRAphyHQv9VcMsv9sf8kBN",
    img: "/grade10/grade10-agri",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "ගෘහ ආර්ථික විද්‍යාව",
    description:
      "10 ශ්‍රේණිය ගෘහ ආර්ථික විද්‍යාව අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1tM4fpX0bm2r3LSLBnTPmpM3Ip04Wc571",
    img: "/grade10/grade10-homeScience",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "සෞඛ්‍ය හා ශාරිරික අධ්‍යාපනය",
    description:
      "10 ශ්‍රේණිය සෞඛ්‍ය හා ශාරිරික අධ්‍යාපනය විද්‍යාව අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1H0sVv-K8LgOxS4YwMSyExeuGFxwAiD0t",
    img: "/grade10/grade10-health",
  },
  {
    grade: "10 ශ්‍රේණිය",
    subject: "තොරතුරු හා සන්නිවේදන තාක්ෂණය",
    description:
      "10 ශ්‍රේණිය තොරතුරු හා සන්නිවේදන තාක්ෂණය අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1tnkMNdAQMyhTW-dPSiOzUj2UScPozFhI",
    img: "/grade10/grade10-ict",
  },
];

// =============================== GRADE 11 ==================================
export const Grade11 = [
  {
    grade: "11 ශ්‍රේණිය",
    subject: "ගණිතය",
    description: "11 ශ්‍රේණිය ගණිතය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1Ry8yDmUAvuinsUEHbck_zcnIjn7tn2aH",
    img: "/grade11/grade11-math",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "විද්‍යාව",
    description: "11 ශ්‍රේණිය විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1WjU5uYIYIlJyFshFPPsK_-w32ieVirej",
    img: "/grade11/grade11-science",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "සිංහල",
    description: "11 ශ්‍රේණිය සිංහල කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1bpb63-Cq97gbYOB8H8VBJOEDgAIW2UpL",
    img: "/grade11/grade11-sinhala",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "ඉංග්‍රීසි",
    description: "11 ශ්‍රේණිය ඉංග්‍රීසි කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1WWLm7PRFvgqxIB_OmEJnEgVZByLDbzq1",
    img: "/grade11/grade11-english",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "බුද්ධ ධර්මය",
    description: "11 ශ්‍රේණිය බුද්ධ ධර්මය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1IEiO6vPGj9GfNUlB_GrCFuIXafGuve_2",
    img: "/grade11/grade11-buddhism",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "ඉතිහාසය",
    description: "11 ශ්‍රේණිය ඉතිහාසය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1r-kPkUg5XhS2IqW6MDmJh2mdZA2faWmW",
    img: "/grade11/grade11-history",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "පුරවැසි අධ්‍යාපනය",
    description: "11 ශ්‍රේණිය පුරවැසි අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1SYZEHye2QOjdWXWiFvkKgiJJ-ZWjSU88",
    img: "/grade11/grade11-civic",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "ව්‍යවසායකත්ව අධ්‍යනය",
    description: "11 ශ්‍රේණිය ව්‍යවසායකත්ව අධ්‍යනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1TeYNnIWxMFdfcIxmiI33RczSegaGBeiJ",
    img: "/grade11/grade11-entrepreneurship",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "භූගෝල විද්‍යාව",
    description: "11 ශ්‍රේණිය භූගෝල විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1mYij3FRHsLx5UWCG9jwNggWo_nxNiz2n",
    img: "/grade11/grade11-geography",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "ව්‍යාපාර හා ගිණුම්කරණය",
    description: "11 ශ්‍රේණිය ව්‍යාපාර හා ගිණුම්කරණය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1AdyEG0yH3DnqzpAQADy_Z0NmYgQyMCJT",
    img: "/grade11/grade11-business",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "දෙවන භාෂාව දෙමළ",
    description: "11 ශ්‍රේණිය දෙවන භාෂාව දෙමළ කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1_uHzg1__tpzbjz3DjI8XC6hLpI0fROjg",
    img: "/grade11/grade11-tamil",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "සිංහල සාහිත්‍ය",
    description: "11 ශ්‍රේණිය සිංහල සාහිත්‍ය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1lvPQIcpyzQPwlCIU8BZmM_u81u1n1etO",
    img: "/grade11/grade11-sinhalaLit",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "චිත්‍ර",
    description: "11 ශ්‍රේණිය චිත්‍ර කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1dPRK7-VXGCm-TqmrE54m_f6lRqWMgGen",
    img: "/grade11/grade11-art",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "නැටුම්",
    description: "11 ශ්‍රේණිය නැටුම් කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1rNokojPoQjMlMG_3k3hslT05zKU7TVjp",
    img: "/grade11/grade11-dance",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "සංගීතය",
    description: "11 ශ්‍රේණිය සංගීතය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1wN_PHou5pUcKh-fUseufJ0GdcsAx9MJS",
    img: "/grade11/grade11-music",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "නාට්‍ය හා රංග කලාව",
    description: "11 ශ්‍රේණිය නාට්‍ය හා රංග කලාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1U2NEr1S6pPQ96TGmb9GHx5nGIWXCy7X_",
    img: "/grade11/grade11-drama",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "කෘෂිකර්මය",
    description: "11 ශ්‍රේණිය කෘෂිකර්මය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1jlyfQn62CnXlFolwyaV52rhIilAcf_hW",
    img: "/grade11/grade11-agri",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "ගෘහ ආර්ථික විද්‍යාව",
    description: "11 ශ්‍රේණිය ගෘහ ආර්ථික විද්‍යාව කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "14pty-hAEszHHRdI-znD448ovlGaVCJpm",
    img: "/grade11/grade11-homeScience",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය",
    description:
      "11 ශ්‍රේණිය සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1J4_0B6EiO97lZf3GTwY2mBwXB4t0UccH",
    img: "/grade11/grade11-health",
  },
  {
    grade: "11 ශ්‍රේණිය",
    subject: "තොරතුරු හා සන්නිවේදන තාක්ෂණය",
    description:
      "11 ශ්‍රේණිය තොරතුරු හා සන්නිවේදන තාක්ෂණය කාර්ය පත්‍රිකා සංග්‍රහය.",
    link: "1a_duV83fm5taaPfNVGSNeCj-_NT7ir9A",
    img: "/grade11/grade11-ict",
  },
];
